# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-management
spec:
  replicas: 3
  selector:
    matchLabels:
      app: task-management
  template:
    metadata:
      labels:
        app: task-management
    spec:
      containers:
      - name: backend
        image: task-management-backend:latest
        ports:
        - containerPort: 8080
      - name: frontend
        image: task-management-frontend:latest
        ports:
        - containerPort: 3000